const customerData: Array<any> = [
  {
    id: 1,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
  {
    id: 2,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
  {
    id: 3,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
  {
    id: 4,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
  {
    id: 5,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
  {
    id: 6,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
  {
    id: 7,
    name: 'Leanne Graham',
    address: 'Apt. 556, 9087 Stang Rd.',
    phone: '1-770-736-8031',
    email: 'info@infos.com',
    domain: 'infos.com',
    database: 'infos',
    active: true,
  },
];

export default customerData;
